name: Sum Random and Multiply Random And Push to DB
author: xyz@company.com
description: This pipeline generates a random integer, passes it to the next task
  that creates and sums another random integer, repeat for multiplication by 2, then
  pushes results to a database.
version: 0.0.1
pipeline:
  executor: sequential
  secrets: .env
  tasks:
  - name: create-first-random-number
    description: Generates a random number
    function:
      source: src.utils.RandomNumber
      params: null
      output:
      - id: randum-num-1
        type: int
    dependencies: null
    requires: null
  - name: sum-first-to-second-random
    description: Takes input from first task and adds second random
    function:
      source: src.utils.add
      params:
      - type: int
        value: random-num-1
      output:
      - id: randum-num-2
        type: int
    dependencies:
      - create-first-random-number
    requires: null
  - name: multiply-randoms-by-2
    description: Takes input from final addition step and multiplies by 2
    function:
      source: src.utils.multiply
      params:
      - type: int
        value: random-num-2
      - type: int
        value: 2
      output:
      - id: final-number
        type: int
    dependencies:
      - sum-first-to-second-random
    requires: null
  - name: push-to-db
    description: Persists database with final number
    function:
      source: jiggy.PostgresExecute
      config:
        dbname: secrets.pg_dbname
        host: secrets.pg_host
        password: secrets.pg_password
        port: secrets.pg_port
        username: secrets.pg_username
      params:
      - data:
        - type: int
          value: final-number
        - type: datetime
          value: now
        query: INSERT INTO schema.table (num, stamp) VALUES (%s, %s)
      output: null
      dependencies:
        - multiply-randoms
      requires: null
